In [36]:
import polars as pl
from tqdm import tqdm
import numpy as np

In [37]:
df = pl.read_csv('/home/dangnh36/datasets/ecg/processed/keypoints_by_model.csv')
df

shape: (8_793, 5)
┌────────────┬─────────┬──────────┬───────────────────────┬─────────────────────────────────┐
│ id         ┆ type_id ┆ rot_code ┆ H                     ┆ keypoints                       │
│ ---        ┆ ---     ┆ ---      ┆ ---                   ┆ ---                             │
│ i64        ┆ i64     ┆ f64      ┆ str                   ┆ str                             │
╞════════════╪═════════╪══════════╪═══════════════════════╪═════════════════════════════════╡
│ 1449491391 ┆ 1       ┆ null     ┆ null                  ┆ {'g_0_1': [39.37007874015748, … │
│ 1449491391 ┆ 3       ┆ null     ┆ [[1.0463203348119845, ┆ {'g_0_1': [71.31941986083984, … │
│            ┆         ┆          ┆ 0.002342…             ┆                                 │
│ 1449491391 ┆ 4       ┆ null     ┆ [[1.04500532394059,   ┆ {'g_0_1': [63.318851470947266,… │
│            ┆         ┆          ┆ -0.0077051…           ┆                                 │
│ 1449491391 ┆ 5       ┆ null     ┆ [[0.7972234573367881, ┆ {'g_0_1': [626.5728149414062, … │
│            ┆         ┆          ┆ 0.068658…             ┆                                 │
│ 1449491391 ┆ 6       ┆ null     ┆ [[0.8146990605192405, ┆ {'g_0_1': [174.14447021484375,… │
│            ┆         ┆          ┆ 0.009941…             ┆                                 │
│ …          ┆ …       ┆ …        ┆ …                     ┆ …                               │
│ 3817987033 ┆ 6       ┆ null     ┆ [[0.6944205329843228, ┆ {'g_0_1': [422.70196533203125,… │
│            ┆         ┆          ┆ 0.042726…             ┆                                 │
│ 3817987033 ┆ 9       ┆ null     ┆ [[0.6790596186459068, ┆ {'g_0_1': [538.113037109375, 2… │
│            ┆         ┆          ┆ -0.00251…             ┆                                 │
│ 3817987033 ┆ 10      ┆ null     ┆ [[0.5703740118479012, ┆ {'g_0_1': [198.09669494628906,… │
│            ┆         ┆          ┆ -0.00506…             ┆                                 │
│ 3817987033 ┆ 11      ┆ null     ┆ [[1.054806937395275,  ┆ {'g_0_1': [63.45686340332031, … │
│            ┆         ┆          ┆ -0.007406…            ┆                                 │
│ 3817987033 ┆ 12      ┆ null     ┆ [[1.0544698462767077, ┆ {'g_0_1': [58.25688171386719, … │
│            ┆         ┆          ┆ -0.00837…             ┆                                 │
└────────────┴─────────┴──────────┴───────────────────────┴─────────────────────────────────┘

In [40]:
df['type_id'].unique().to_list()

[1, 3, 4, 5, 6, 9, 10, 11, 12]

In [26]:
df.group_by('id').len('len_per_id').group_by('len_per_id').len()

shape: (1, 2)
┌────────────┬─────┐
│ len_per_id ┆ len │
│ ---        ┆ --- │
│ u32        ┆ u32 │
╞════════════╪═════╡
│ 9          ┆ 977 │
└────────────┴─────┘

In [27]:
# len([e for e in KPT_NAMES if e.startswith('g_')])

In [28]:
KPT_NAMES = None
all_xys = []
for row in tqdm(df.iter_rows(named = True)):
    kpts = eval(row['keypoints'])
    kpt_names = list(kpts.keys())
    kpt_xys = np.array(list(kpts.values()))
    all_xys.append(kpt_xys)
    if KPT_NAMES is None:
        KPT_NAMES = kpt_names
        print(KPT_NAMES)
    assert KPT_NAMES == kpt_names

17it [00:00, 80.57it/s]

['g_0_1', 'g_0_2', 'g_0_3', 'g_0_4', 'g_0_5', 'g_0_6', 'g_0_7', 'g_0_8', 'g_0_9', 'g_0_10', 'g_0_11', 'g_0_12', 'g_0_13', 'g_0_14', 'g_0_15', 'g_0_16', 'g_0_17', 'g_0_18', 'g_0_19', 'g_0_20', 'g_0_21', 'g_0_22', 'g_0_23', 'g_0_24', 'g_0_25', 'g_0_26', 'g_0_27', 'g_0_28', 'g_0_29', 'g_0_30', 'g_0_31', 'g_0_32', 'g_0_33', 'g_0_34', 'g_0_35', 'g_0_36', 'g_0_37', 'g_0_38', 'g_0_39', 'g_0_40', 'g_0_41', 'g_0_42', 'g_0_43', 'g_0_44', 'g_0_45', 'g_0_46', 'g_0_47', 'g_0_48', 'g_0_49', 'g_0_50', 'g_0_51', 'g_0_52', 'g_0_53', 'g_0_54', 'g_0_55', 'g_1_1', 'g_1_2', 'g_1_3', 'g_1_4', 'g_1_5', 'g_1_6', 'g_1_7', 'g_1_8', 'g_1_9', 'g_1_10', 'g_1_11', 'g_1_12', 'g_1_13', 'g_1_14', 'g_1_15', 'g_1_16', 'g_1_17', 'g_1_18', 'g_1_19', 'g_1_20', 'g_1_21', 'g_1_22', 'g_1_23', 'g_1_24', 'g_1_25', 'g_1_26', 'g_1_27', 'g_1_28', 'g_1_29', 'g_1_30', 'g_1_31', 'g_1_32', 'g_1_33', 'g_1_34', 'g_1_35', 'g_1_36', 'g_1_37', 'g_1_38', 'g_1_39', 'g_1_40', 'g_1_41', 'g_1_42', 'g_1_43', 'g_1_44', 'g_1_45', 'g_1_46', 'g_1_47', 'g_1_48', 'g_1_49', 'g_1_50', 'g_1_51', 'g_1_52', 'g_1_53', 'g_1_54', 'g_1_55', 'g_2_1', 'g_2_2', 'g_2_3', 'g_2_4', 'g_2_5', 'g_2_6', 'g_2_7', 'g_2_8', 'g_2_9', 'g_2_10', 'g_2_11', 'g_2_12', 'g_2_13', 'g_2_14', 'g_2_15', 'g_2_16', 'g_2_17', 'g_2_18', 'g_2_19', 'g_2_20', 'g_2_21', 'g_2_22', 'g_2_23', 'g_2_24', 'g_2_25', 'g_2_26', 'g_2_27', 'g_2_28', 'g_2_29', 'g_2_30', 'g_2_31', 'g_2_32', 'g_2_33', 'g_2_34', 'g_2_35', 'g_2_36', 'g_2_37', 'g_2_38', 'g_2_39', 'g_2_40', 'g_2_41', 'g_2_42', 'g_2_43', 'g_2_44', 'g_2_45', 'g_2_46', 'g_2_47', 'g_2_48', 'g_2_49', 'g_2_50', 'g_2_51', 'g_2_52', 'g_2_53', 'g_2_54', 'g_2_55', 'g_3_1', 'g_3_2', 'g_3_3', 'g_3_4', 'g_3_5', 'g_3_6', 'g_3_7', 'g_3_8', 'g_3_9', 'g_3_10', 'g_3_11', 'g_3_12', 'g_3_13', 'g_3_14', 'g_3_15', 'g_3_16', 'g_3_17', 'g_3_18', 'g_3_19', 'g_3_20', 'g_3_21', 'g_3_22', 'g_3_23', 'g_3_24', 'g_3_25', 'g_3_26', 'g_3_27', 'g_3_28', 'g_3_29', 'g_3_30', 'g_3_31', 'g_3_32', 'g_3_33', 'g_3_34', 'g_3_35', 'g_3_36', 'g_3_37', 'g_3_38', 'g_3_39', 'g_3_40', 'g_3_41', 'g_3_42', 'g_3_43', 'g_3_44', 'g_3_45', 'g_3_46', 'g_3_47', 'g_3_48', 'g_3_49', 'g_3_50', 'g_3_51', 'g_3_52', 'g_3_53', 'g_3_54', 'g_3_55', 'g_4_1', 'g_4_2', 'g_4_3', 'g_4_4', 'g_4_5', 'g_4_6', 'g_4_7', 'g_4_8', 'g_4_9', 'g_4_10', 'g_4_11', 'g_4_12', 'g_4_13', 'g_4_14', 'g_4_15', 'g_4_16', 'g_4_17', 'g_4_18', 'g_4_19', 'g_4_20', 'g_4_21', 'g_4_22', 'g_4_23', 'g_4_24', 'g_4_25', 'g_4_26', 'g_4_27', 'g_4_28', 'g_4_29', 'g_4_30', 'g_4_31', 'g_4_32', 'g_4_33', 'g_4_34', 'g_4_35', 'g_4_36', 'g_4_37', 'g_4_38', 'g_4_39', 'g_4_40', 'g_4_41', 'g_4_42', 'g_4_43', 'g_4_44', 'g_4_45', 'g_4_46', 'g_4_47', 'g_4_48', 'g_4_49', 'g_4_50', 'g_4_51', 'g_4_52', 'g_4_53', 'g_4_54', 'g_4_55', 'g_5_1', 'g_5_2', 'g_5_3', 'g_5_4', 'g_5_5', 'g_5_6', 'g_5_7', 'g_5_8', 'g_5_9', 'g_5_10', 'g_5_11', 'g_5_12', 'g_5_13', 'g_5_14', 'g_5_15', 'g_5_16', 'g_5_17', 'g_5_18', 'g_5_19', 'g_5_20', 'g_5_21', 'g_5_22', 'g_5_23', 'g_5_24', 'g_5_25', 'g_5_26', 'g_5_27', 'g_5_28', 'g_5_29', 'g_5_30', 'g_5_31', 'g_5_32', 'g_5_33', 'g_5_34', 'g_5_35', 'g_5_36', 'g_5_37', 'g_5_38', 'g_5_39', 'g_5_40', 'g_5_41', 'g_5_42', 'g_5_43', 'g_5_44', 'g_5_45', 'g_5_46', 'g_5_47', 'g_5_48', 'g_5_49', 'g_5_50', 'g_5_51', 'g_5_52', 'g_5_53', 'g_5_54', 'g_5_55', 'g_6_1', 'g_6_2', 'g_6_3', 'g_6_4', 'g_6_5', 'g_6_6', 'g_6_7', 'g_6_8', 'g_6_9', 'g_6_10', 'g_6_11', 'g_6_12', 'g_6_13', 'g_6_14', 'g_6_15', 'g_6_16', 'g_6_17', 'g_6_18', 'g_6_19', 'g_6_20', 'g_6_21', 'g_6_22', 'g_6_23', 'g_6_24', 'g_6_25', 'g_6_26', 'g_6_27', 'g_6_28', 'g_6_29', 'g_6_30', 'g_6_31', 'g_6_32', 'g_6_33', 'g_6_34', 'g_6_35', 'g_6_36', 'g_6_37', 'g_6_38', 'g_6_39', 'g_6_40', 'g_6_41', 'g_6_42', 'g_6_43', 'g_6_44', 'g_6_45', 'g_6_46', 'g_6_47', 'g_6_48', 'g_6_49', 'g_6_50', 'g_6_51', 'g_6_52', 'g_6_53', 'g_6_54', 'g_6_55', 'g_7_1', 'g_7_2', 'g_7_3', 'g_7_4', 'g_7_5', 'g_7_6', 'g_7_7', 'g_7_8', 'g_7_9', 'g_7_10', 'g_7_11', 'g_7_12', 'g_7_13', 'g_7_14', 'g_7_15', 'g_7_16', 'g_7_17', 'g_7_18', 'g_7_19', 'g_7_20', 'g_7_21', 'g_7_22', 'g_7_23', 'g_7_24', 'g_7_25', 'g_7_26', 'g_7_27', 'g_7_28', 'g_7_29', 'g_7_30', 'g_7_31', 'g_7_32', 'g_7_33', 'g_7_34', 'g_7_35', 'g_7_36', 'g_7_37', 'g_7_38', 'g_7_39', 'g_7_40', 'g_7_41', 'g_7_42', 'g_7_43', 'g_7_44', 'g_7_45', 'g_7_46', 'g_7_47', 'g_7_48', 'g_7_49', 'g_7_50', 'g_7_51', 'g_7_52', 'g_7_53', 'g_7_54', 'g_7_55', 'g_8_1', 'g_8_2', 'g_8_3', 'g_8_4', 'g_8_5', 'g_8_6', 'g_8_7', 'g_8_8', 'g_8_9', 'g_8_10', 'g_8_11', 'g_8_12', 'g_8_13', 'g_8_14', 'g_8_15', 'g_8_16', 'g_8_17', 'g_8_18', 'g_8_19', 'g_8_20', 'g_8_21', 'g_8_22', 'g_8_23', 'g_8_24', 'g_8_25', 'g_8_26', 'g_8_27', 'g_8_28', 'g_8_29', 'g_8_30', 'g_8_31', 'g_8_32', 'g_8_33', 'g_8_34', 'g_8_35', 'g_8_36', 'g_8_37', 'g_8_38', 'g_8_39', 'g_8_40', 'g_8_41', 'g_8_42', 'g_8_43', 'g_8_44', 'g_8_45', 'g_8_46', 'g_8_47', 'g_8_48', 'g_8_49', 'g_8_50', 'g_8_51', 'g_8_52', 'g_8_53', 'g_8_54', 'g_8_55', 'g_9_1', 'g_9_2', 'g_9_3', 'g_9_4', 'g_9_5', 'g_9_6', 'g_9_7', 'g_9_8', 'g_9_9', 'g_9_10', 'g_9_11', 'g_9_12', 'g_9_13', 'g_9_14', 'g_9_15', 'g_9_16', 'g_9_17', 'g_9_18', 'g_9_19', 'g_9_20', 'g_9_21', 'g_9_22', 'g_9_23', 'g_9_24', 'g_9_25', 'g_9_26', 'g_9_27', 'g_9_28', 'g_9_29', 'g_9_30', 'g_9_31', 'g_9_32', 'g_9_33', 'g_9_34', 'g_9_35', 'g_9_36', 'g_9_37', 'g_9_38', 'g_9_39', 'g_9_40', 'g_9_41', 'g_9_42', 'g_9_43', 'g_9_44', 'g_9_45', 'g_9_46', 'g_9_47', 'g_9_48', 'g_9_49', 'g_9_50', 'g_9_51', 'g_9_52', 'g_9_53', 'g_9_54', 'g_9_55', 'g_10_1', 'g_10_2', 'g_10_3', 'g_10_4', 'g_10_5', 'g_10_6', 'g_10_7', 'g_10_8', 'g_10_9', 'g_10_10', 'g_10_11', 'g_10_12', 'g_10_13', 'g_10_14', 'g_10_15', 'g_10_16', 'g_10_17', 'g_10_18', 'g_10_19', 'g_10_20', 'g_10_21', 'g_10_22', 'g_10_23', 'g_10_24', 'g_10_25', 'g_10_26', 'g_10_27', 'g_10_28', 'g_10_29', 'g_10_30', 'g_10_31', 'g_10_32', 'g_10_33', 'g_10_34', 'g_10_35', 'g_10_36', 'g_10_37', 'g_10_38', 'g_10_39', 'g_10_40', 'g_10_41', 'g_10_42', 'g_10_43', 'g_10_44', 'g_10_45', 'g_10_46', 'g_10_47', 'g_10_48', 'g_10_49', 'g_10_50', 'g_10_51', 'g_10_52', 'g_10_53', 'g_10_54', 'g_10_55', 'g_11_1', 'g_11_2', 'g_11_3', 'g_11_4', 'g_11_5', 'g_11_6', 'g_11_7', 'g_11_8', 'g_11_9', 'g_11_10', 'g_11_11', 'g_11_12', 'g_11_13', 'g_11_14', 'g_11_15', 'g_11_16', 'g_11_17', 'g_11_18', 'g_11_19', 'g_11_20', 'g_11_21', 'g_11_22', 'g_11_23', 'g_11_24', 'g_11_25', 'g_11_26', 'g_11_27', 'g_11_28', 'g_11_29', 'g_11_30', 'g_11_31', 'g_11_32', 'g_11_33', 'g_11_34', 'g_11_35', 'g_11_36', 'g_11_37', 'g_11_38', 'g_11_39', 'g_11_40', 'g_11_41', 'g_11_42', 'g_11_43', 'g_11_44', 'g_11_45', 'g_11_46', 'g_11_47', 'g_11_48', 'g_11_49', 'g_11_50', 'g_11_51', 'g_11_52', 'g_11_53', 'g_11_54', 'g_11_55', 'g_12_1', 'g_12_2', 'g_12_3', 'g_12_4', 'g_12_5', 'g_12_6', 'g_12_7', 'g_12_8', 'g_12_9', 'g_12_10', 'g_12_11', 'g_12_12', 'g_12_13', 'g_12_14', 'g_12_15', 'g_12_16', 'g_12_17', 'g_12_18', 'g_12_19', 'g_12_20', 'g_12_21', 'g_12_22', 'g_12_23', 'g_12_24', 'g_12_25', 'g_12_26', 'g_12_27', 'g_12_28', 'g_12_29', 'g_12_30', 'g_12_31', 'g_12_32', 'g_12_33', 'g_12_34', 'g_12_35', 'g_12_36', 'g_12_37', 'g_12_38', 'g_12_39', 'g_12_40', 'g_12_41', 'g_12_42', 'g_12_43', 'g_12_44', 'g_12_45', 'g_12_46', 'g_12_47', 'g_12_48', 'g_12_49', 'g_12_50', 'g_12_51', 'g_12_52', 'g_12_53', 'g_12_54', 'g_12_55', 'g_13_1', 'g_13_2', 'g_13_3', 'g_13_4', 'g_13_5', 'g_13_6', 'g_13_7', 'g_13_8', 'g_13_9', 'g_13_10', 'g_13_11', 'g_13_12', 'g_13_13', 'g_13_14', 'g_13_15', 'g_13_16', 'g_13_17', 'g_13_18', 'g_13_19', 'g_13_20', 'g_13_21', 'g_13_22', 'g_13_23', 'g_13_24', 'g_13_25', 'g_13_26', 'g_13_27', 'g_13_28', 'g_13_29', 'g_13_30', 'g_13_31', 'g_13_32', 'g_13_33', 'g_13_34', 'g_13_35', 'g_13_36', 'g_13_37', 'g_13_38', 'g_13_39', 'g_13_40', 'g_13_41', 'g_13_42', 'g_13_43', 'g_13_44', 'g_13_45', 'g_13_46', 'g_13_47', 'g_13_48', 'g_13_49', 'g_13_50', 'g_13_51', 'g_13_52', 'g_13_53', 'g_13_54', 'g_13_55', 'g_14_1', 'g_14_2', 'g_14_3', 'g_14_4', 'g_14_5', 'g_14_6', 'g_14_7', 'g_14_8', 'g_14_9', 'g_14_10', 'g_14_11', 'g_14_12', 'g_14_13', 'g_14_14', 'g_14_15', 'g_14_16', 'g_14_17', 'g_14_18', 'g_14_19', 'g_14_20', 'g_14_21', 'g_14_22', 'g_14_23', 'g_14_24', 'g_14_25', 'g_14_26', 'g_14_27', 'g_14_28', 'g_14_29', 'g_14_30', 'g_14_31', 'g_14_32', 'g_14_33', 'g_14_34', 'g_14_35', 'g_14_36', 'g_14_37', 'g_14_38', 'g_14_39', 'g_14_40', 'g_14_41', 'g_14_42', 'g_14_43', 'g_14_44', 'g_14_45', 'g_14_46', 'g_14_47', 'g_14_48', 'g_14_49', 'g_14_50', 'g_14_51', 'g_14_52', 'g_14_53', 'g_14_54', 'g_14_55', 'g_15_1', 'g_15_2', 'g_15_3', 'g_15_4', 'g_15_5', 'g_15_6', 'g_15_7', 'g_15_8', 'g_15_9', 'g_15_10', 'g_15_11', 'g_15_12', 'g_15_13', 'g_15_14', 'g_15_15', 'g_15_16', 'g_15_17', 'g_15_18', 'g_15_19', 'g_15_20', 'g_15_21', 'g_15_22', 'g_15_23', 'g_15_24', 'g_15_25', 'g_15_26', 'g_15_27', 'g_15_28', 'g_15_29', 'g_15_30', 'g_15_31', 'g_15_32', 'g_15_33', 'g_15_34', 'g_15_35', 'g_15_36', 'g_15_37', 'g_15_38', 'g_15_39', 'g_15_40', 'g_15_41', 'g_15_42', 'g_15_43', 'g_15_44', 'g_15_45', 'g_15_46', 'g_15_47', 'g_15_48', 'g_15_49', 'g_15_50', 'g_15_51', 'g_15_52', 'g_15_53', 'g_15_54', 'g_15_55', 'g_16_1', 'g_16_2', 'g_16_3', 'g_16_4', 'g_16_5', 'g_16_6', 'g_16_7', 'g_16_8', 'g_16_9', 'g_16_10', 'g_16_11', 'g_16_12', 'g_16_13', 'g_16_14', 'g_16_15', 'g_16_16', 'g_16_17', 'g_16_18', 'g_16_19', 'g_16_20', 'g_16_21', 'g_16_22', 'g_16_23', 'g_16_24', 'g_16_25', 'g_16_26', 'g_16_27', 'g_16_28', 'g_16_29', 'g_16_30', 'g_16_31', 'g_16_32', 'g_16_33', 'g_16_34', 'g_16_35', 'g_16_36', 'g_16_37', 'g_16_38', 'g_16_39', 'g_16_40', 'g_16_41', 'g_16_42', 'g_16_43', 'g_16_44', 'g_16_45', 'g_16_46', 'g_16_47', 'g_16_48', 'g_16_49', 'g_16_50', 'g_16_51', 'g_16_52', 'g_16_53', 'g_16_54', 'g_16_55', 'g_17_1', 'g_17_2', 'g_17_3', 'g_17_4', 'g_17_5', 'g_17_6', 'g_17_7', 'g_17_8', 'g_17_9', 'g_17_10', 'g_17_11', 'g_17_12', 'g_17_13', 'g_17_14', 'g_17_15', 'g_17_16', 'g_17_17', 'g_17_18', 'g_17_19', 'g_17_20', 'g_17_21', 'g_17_22', 'g_17_23', 'g_17_24', 'g_17_25', 'g_17_26', 'g_17_27', 'g_17_28', 'g_17_29', 'g_17_30', 'g_17_31', 'g_17_32', 'g_17_33', 'g_17_34', 'g_17_35', 'g_17_36', 'g_17_37', 'g_17_38', 'g_17_39', 'g_17_40', 'g_17_41', 'g_17_42', 'g_17_43', 'g_17_44', 'g_17_45', 'g_17_46', 'g_17_47', 'g_17_48', 'g_17_49', 'g_17_50', 'g_17_51', 'g_17_52', 'g_17_53', 'g_17_54', 'g_17_55', 'g_18_1', 'g_18_2', 'g_18_3', 'g_18_4', 'g_18_5', 'g_18_6', 'g_18_7', 'g_18_8', 'g_18_9', 'g_18_10', 'g_18_11', 'g_18_12', 'g_18_13', 'g_18_14', 'g_18_15', 'g_18_16', 'g_18_17', 'g_18_18', 'g_18_19', 'g_18_20', 'g_18_21', 'g_18_22', 'g_18_23', 'g_18_24', 'g_18_25', 'g_18_26', 'g_18_27', 'g_18_28', 'g_18_29', 'g_18_30', 'g_18_31', 'g_18_32', 'g_18_33', 'g_18_34', 'g_18_35', 'g_18_36', 'g_18_37', 'g_18_38', 'g_18_39', 'g_18_40', 'g_18_41', 'g_18_42', 'g_18_43', 'g_18_44', 'g_18_45', 'g_18_46', 'g_18_47', 'g_18_48', 'g_18_49', 'g_18_50', 'g_18_51', 'g_18_52', 'g_18_53', 'g_18_54', 'g_18_55', 'g_19_1', 'g_19_2', 'g_19_3', 'g_19_4', 'g_19_5', 'g_19_6', 'g_19_7', 'g_19_8', 'g_19_9', 'g_19_10', 'g_19_11', 'g_19_12', 'g_19_13', 'g_19_14', 'g_19_15', 'g_19_16', 'g_19_17', 'g_19_18', 'g_19_19', 'g_19_20', 'g_19_21', 'g_19_22', 'g_19_23', 'g_19_24', 'g_19_25', 'g_19_26', 'g_19_27', 'g_19_28', 'g_19_29', 'g_19_30', 'g_19_31', 'g_19_32', 'g_19_33', 'g_19_34', 'g_19_35', 'g_19_36', 'g_19_37', 'g_19_38', 'g_19_39', 'g_19_40', 'g_19_41', 'g_19_42', 'g_19_43', 'g_19_44', 'g_19_45', 'g_19_46', 'g_19_47', 'g_19_48', 'g_19_49', 'g_19_50', 'g_19_51', 'g_19_52', 'g_19_53', 'g_19_54', 'g_19_55', 'g_20_1', 'g_20_2', 'g_20_3', 'g_20_4', 'g_20_5', 'g_20_6', 'g_20_7', 'g_20_8', 'g_20_9', 'g_20_10', 'g_20_11', 'g_20_12', 'g_20_13', 'g_20_14', 'g_20_15', 'g_20_16', 'g_20_17', 'g_20_18', 'g_20_19', 'g_20_20', 'g_20_21', 'g_20_22', 'g_20_23', 'g_20_24', 'g_20_25', 'g_20_26', 'g_20_27', 'g_20_28', 'g_20_29', 'g_20_30', 'g_20_31', 'g_20_32', 'g_20_33', 'g_20_34', 'g_20_35', 'g_20_36', 'g_20_37', 'g_20_38', 'g_20_39', 'g_20_40', 'g_20_41', 'g_20_42', 'g_20_43', 'g_20_44', 'g_20_45', 'g_20_46', 'g_20_47', 'g_20_48', 'g_20_49', 'g_20_50', 'g_20_51', 'g_20_52', 'g_20_53', 'g_20_54', 'g_20_55', 'g_21_1', 'g_21_2', 'g_21_3', 'g_21_4', 'g_21_5', 'g_21_6', 'g_21_7', 'g_21_8', 'g_21_9', 'g_21_10', 'g_21_11', 'g_21_12', 'g_21_13', 'g_21_14', 'g_21_15', 'g_21_16', 'g_21_17', 'g_21_18', 'g_21_19', 'g_21_20', 'g_21_21', 'g_21_22', 'g_21_23', 'g_21_24', 'g_21_25', 'g_21_26', 'g_21_27', 'g_21_28', 'g_21_29', 'g_21_30', 'g_21_31', 'g_21_32', 'g_21_33', 'g_21_34', 'g_21_35', 'g_21_36', 'g_21_37', 'g_21_38', 'g_21_39', 'g_21_40', 'g_21_41', 'g_21_42', 'g_21_43', 'g_21_44', 'g_21_45', 'g_21_46', 'g_21_47', 'g_21_48', 'g_21_49', 'g_21_50', 'g_21_51', 'g_21_52', 'g_21_53', 'g_21_54', 'g_21_55', 'g_22_1', 'g_22_2', 'g_22_3', 'g_22_4', 'g_22_5', 'g_22_6', 'g_22_7', 'g_22_8', 'g_22_9', 'g_22_10', 'g_22_11', 'g_22_12', 'g_22_13', 'g_22_14', 'g_22_15', 'g_22_16', 'g_22_17', 'g_22_18', 'g_22_19', 'g_22_20', 'g_22_21', 'g_22_22', 'g_22_23', 'g_22_24', 'g_22_25', 'g_22_26', 'g_22_27', 'g_22_28', 'g_22_29', 'g_22_30', 'g_22_31', 'g_22_32', 'g_22_33', 'g_22_34', 'g_22_35', 'g_22_36', 'g_22_37', 'g_22_38', 'g_22_39', 'g_22_40', 'g_22_41', 'g_22_42', 'g_22_43', 'g_22_44', 'g_22_45', 'g_22_46', 'g_22_47', 'g_22_48', 'g_22_49', 'g_22_50', 'g_22_51', 'g_22_52', 'g_22_53', 'g_22_54', 'g_22_55', 'g_23_1', 'g_23_2', 'g_23_3', 'g_23_4', 'g_23_5', 'g_23_6', 'g_23_7', 'g_23_8', 'g_23_9', 'g_23_10', 'g_23_11', 'g_23_12', 'g_23_13', 'g_23_14', 'g_23_15', 'g_23_16', 'g_23_17', 'g_23_18', 'g_23_19', 'g_23_20', 'g_23_21', 'g_23_22', 'g_23_23', 'g_23_24', 'g_23_25', 'g_23_26', 'g_23_27', 'g_23_28', 'g_23_29', 'g_23_30', 'g_23_31', 'g_23_32', 'g_23_33', 'g_23_34', 'g_23_35', 'g_23_36', 'g_23_37', 'g_23_38', 'g_23_39', 'g_23_40', 'g_23_41', 'g_23_42', 'g_23_43', 'g_23_44', 'g_23_45', 'g_23_46', 'g_23_47', 'g_23_48', 'g_23_49', 'g_23_50', 'g_23_51', 'g_23_52', 'g_23_53', 'g_23_54', 'g_23_55', 'g_24_1', 'g_24_2', 'g_24_3', 'g_24_4', 'g_24_5', 'g_24_6', 'g_24_7', 'g_24_8', 'g_24_9', 'g_24_10', 'g_24_11', 'g_24_12', 'g_24_13', 'g_24_14', 'g_24_15', 'g_24_16', 'g_24_17', 'g_24_18', 'g_24_19', 'g_24_20', 'g_24_21', 'g_24_22', 'g_24_23', 'g_24_24', 'g_24_25', 'g_24_26', 'g_24_27', 'g_24_28', 'g_24_29', 'g_24_30', 'g_24_31', 'g_24_32', 'g_24_33', 'g_24_34', 'g_24_35', 'g_24_36', 'g_24_37', 'g_24_38', 'g_24_39', 'g_24_40', 'g_24_41', 'g_24_42', 'g_24_43', 'g_24_44', 'g_24_45', 'g_24_46', 'g_24_47', 'g_24_48', 'g_24_49', 'g_24_50', 'g_24_51', 'g_24_52', 'g_24_53', 'g_24_54', 'g_24_55', 'g_25_1', 'g_25_2', 'g_25_3', 'g_25_4', 'g_25_5', 'g_25_6', 'g_25_7', 'g_25_8', 'g_25_9', 'g_25_10', 'g_25_11', 'g_25_12', 'g_25_13', 'g_25_14', 'g_25_15', 'g_25_16', 'g_25_17', 'g_25_18', 'g_25_19', 'g_25_20', 'g_25_21', 'g_25_22', 'g_25_23', 'g_25_24', 'g_25_25', 'g_25_26', 'g_25_27', 'g_25_28', 'g_25_29', 'g_25_30', 'g_25_31', 'g_25_32', 'g_25_33', 'g_25_34', 'g_25_35', 'g_25_36', 'g_25_37', 'g_25_38', 'g_25_39', 'g_25_40', 'g_25_41', 'g_25_42', 'g_25_43', 'g_25_44', 'g_25_45', 'g_25_46', 'g_25_47', 'g_25_48', 'g_25_49', 'g_25_50', 'g_25_51', 'g_25_52', 'g_25_53', 'g_25_54', 'g_25_55', 'g_26_1', 'g_26_2', 'g_26_3', 'g_26_4', 'g_26_5', 'g_26_6', 'g_26_7', 'g_26_8', 'g_26_9', 'g_26_10', 'g_26_11', 'g_26_12', 'g_26_13', 'g_26_14', 'g_26_15', 'g_26_16', 'g_26_17', 'g_26_18', 'g_26_19', 'g_26_20', 'g_26_21', 'g_26_22', 'g_26_23', 'g_26_24', 'g_26_25', 'g_26_26', 'g_26_27', 'g_26_28', 'g_26_29', 'g_26_30', 'g_26_31', 'g_26_32', 'g_26_33', 'g_26_34', 'g_26_35', 'g_26_36', 'g_26_37', 'g_26_38', 'g_26_39', 'g_26_40', 'g_26_41', 'g_26_42', 'g_26_43', 'g_26_44', 'g_26_45', 'g_26_46', 'g_26_47', 'g_26_48', 'g_26_49', 'g_26_50', 'g_26_51', 'g_26_52', 'g_26_53', 'g_26_54', 'g_26_55', 'g_27_1', 'g_27_2', 'g_27_3', 'g_27_4', 'g_27_5', 'g_27_6', 'g_27_7', 'g_27_8', 'g_27_9', 'g_27_10', 'g_27_11', 'g_27_12', 'g_27_13', 'g_27_14', 'g_27_15', 'g_27_16', 'g_27_17', 'g_27_18', 'g_27_19', 'g_27_20', 'g_27_21', 'g_27_22', 'g_27_23', 'g_27_24', 'g_27_25', 'g_27_26', 'g_27_27', 'g_27_28', 'g_27_29', 'g_27_30', 'g_27_31', 'g_27_32', 'g_27_33', 'g_27_34', 'g_27_35', 'g_27_36', 'g_27_37', 'g_27_38', 'g_27_39', 'g_27_40', 'g_27_41', 'g_27_42', 'g_27_43', 'g_27_44', 'g_27_45', 'g_27_46', 'g_27_47', 'g_27_48', 'g_27_49', 'g_27_50', 'g_27_51', 'g_27_52', 'g_27_53', 'g_27_54', 'g_27_55', 'g_28_1', 'g_28_2', 'g_28_3', 'g_28_4', 'g_28_5', 'g_28_6', 'g_28_7', 'g_28_8', 'g_28_9', 'g_28_10', 'g_28_11', 'g_28_12', 'g_28_13', 'g_28_14', 'g_28_15', 'g_28_16', 'g_28_17', 'g_28_18', 'g_28_19', 'g_28_20', 'g_28_21', 'g_28_22', 'g_28_23', 'g_28_24', 'g_28_25', 'g_28_26', 'g_28_27', 'g_28_28', 'g_28_29', 'g_28_30', 'g_28_31', 'g_28_32', 'g_28_33', 'g_28_34', 'g_28_35', 'g_28_36', 'g_28_37', 'g_28_38', 'g_28_39', 'g_28_40', 'g_28_41', 'g_28_42', 'g_28_43', 'g_28_44', 'g_28_45', 'g_28_46', 'g_28_47', 'g_28_48', 'g_28_49', 'g_28_50', 'g_28_51', 'g_28_52', 'g_28_53', 'g_28_54', 'g_28_55', 'g_29_1', 'g_29_2', 'g_29_3', 'g_29_4', 'g_29_5', 'g_29_6', 'g_29_7', 'g_29_8', 'g_29_9', 'g_29_10', 'g_29_11', 'g_29_12', 'g_29_13', 'g_29_14', 'g_29_15', 'g_29_16', 'g_29_17', 'g_29_18', 'g_29_19', 'g_29_20', 'g_29_21', 'g_29_22', 'g_29_23', 'g_29_24', 'g_29_25', 'g_29_26', 'g_29_27', 'g_29_28', 'g_29_29', 'g_29_30', 'g_29_31', 'g_29_32', 'g_29_33', 'g_29_34', 'g_29_35', 'g_29_36', 'g_29_37', 'g_29_38', 'g_29_39', 'g_29_40', 'g_29_41', 'g_29_42', 'g_29_43', 'g_29_44', 'g_29_45', 'g_29_46', 'g_29_47', 'g_29_48', 'g_29_49', 'g_29_50', 'g_29_51', 'g_29_52', 'g_29_53', 'g_29_54', 'g_29_55', 'g_30_1', 'g_30_2', 'g_30_3', 'g_30_4', 'g_30_5', 'g_30_6', 'g_30_7', 'g_30_8', 'g_30_9', 'g_30_10', 'g_30_11', 'g_30_12', 'g_30_13', 'g_30_14', 'g_30_15', 'g_30_16', 'g_30_17', 'g_30_18', 'g_30_19', 'g_30_20', 'g_30_21', 'g_30_22', 'g_30_23', 'g_30_24', 'g_30_25', 'g_30_26', 'g_30_27', 'g_30_28', 'g_30_29', 'g_30_30', 'g_30_31', 'g_30_32', 'g_30_33', 'g_30_34', 'g_30_35', 'g_30_36', 'g_30_37', 'g_30_38', 'g_30_39', 'g_30_40', 'g_30_41', 'g_30_42', 'g_30_43', 'g_30_44', 'g_30_45', 'g_30_46', 'g_30_47', 'g_30_48', 'g_30_49', 'g_30_50', 'g_30_51', 'g_30_52', 'g_30_53', 'g_30_54', 'g_30_55', 'g_31_1', 'g_31_2', 'g_31_3', 'g_31_4', 'g_31_5', 'g_31_6', 'g_31_7', 'g_31_8', 'g_31_9', 'g_31_10', 'g_31_11', 'g_31_12', 'g_31_13', 'g_31_14', 'g_31_15', 'g_31_16', 'g_31_17', 'g_31_18', 'g_31_19', 'g_31_20', 'g_31_21', 'g_31_22', 'g_31_23', 'g_31_24', 'g_31_25', 'g_31_26', 'g_31_27', 'g_31_28', 'g_31_29', 'g_31_30', 'g_31_31', 'g_31_32', 'g_31_33', 'g_31_34', 'g_31_35', 'g_31_36', 'g_31_37', 'g_31_38', 'g_31_39', 'g_31_40', 'g_31_41', 'g_31_42', 'g_31_43', 'g_31_44', 'g_31_45', 'g_31_46', 'g_31_47', 'g_31_48', 'g_31_49', 'g_31_50', 'g_31_51', 'g_31_52', 'g_31_53', 'g_31_54', 'g_31_55', 'g_32_1', 'g_32_2', 'g_32_3', 'g_32_4', 'g_32_5', 'g_32_6', 'g_32_7', 'g_32_8', 'g_32_9', 'g_32_10', 'g_32_11', 'g_32_12', 'g_32_13', 'g_32_14', 'g_32_15', 'g_32_16', 'g_32_17', 'g_32_18', 'g_32_19', 'g_32_20', 'g_32_21', 'g_32_22', 'g_32_23', 'g_32_24', 'g_32_25', 'g_32_26', 'g_32_27', 'g_32_28', 'g_32_29', 'g_32_30', 'g_32_31', 'g_32_32', 'g_32_33', 'g_32_34', 'g_32_35', 'g_32_36', 'g_32_37', 'g_32_38', 'g_32_39', 'g_32_40', 'g_32_41', 'g_32_42', 'g_32_43', 'g_32_44', 'g_32_45', 'g_32_46', 'g_32_47', 'g_32_48', 'g_32_49', 'g_32_50', 'g_32_51', 'g_32_52', 'g_32_53', 'g_32_54', 'g_32_55', 'g_33_1', 'g_33_2', 'g_33_3', 'g_33_4', 'g_33_5', 'g_33_6', 'g_33_7', 'g_33_8', 'g_33_9', 'g_33_10', 'g_33_11', 'g_33_12', 'g_33_13', 'g_33_14', 'g_33_15', 'g_33_16', 'g_33_17', 'g_33_18', 'g_33_19', 'g_33_20', 'g_33_21', 'g_33_22', 'g_33_23', 'g_33_24', 'g_33_25', 'g_33_26', 'g_33_27', 'g_33_28', 'g_33_29', 'g_33_30', 'g_33_31', 'g_33_32', 'g_33_33', 'g_33_34', 'g_33_35', 'g_33_36', 'g_33_37', 'g_33_38', 'g_33_39', 'g_33_40', 'g_33_41', 'g_33_42', 'g_33_43', 'g_33_44', 'g_33_45', 'g_33_46', 'g_33_47', 'g_33_48', 'g_33_49', 'g_33_50', 'g_33_51', 'g_33_52', 'g_33_53', 'g_33_54', 'g_33_55', 'g_34_1', 'g_34_2', 'g_34_3', 'g_34_4', 'g_34_5', 'g_34_6', 'g_34_7', 'g_34_8', 'g_34_9', 'g_34_10', 'g_34_11', 'g_34_12', 'g_34_13', 'g_34_14', 'g_34_15', 'g_34_16', 'g_34_17', 'g_34_18', 'g_34_19', 'g_34_20', 'g_34_21', 'g_34_22', 'g_34_23', 'g_34_24', 'g_34_25', 'g_34_26', 'g_34_27

8793it [01:48, 81.00it/s]

In [29]:
all_xys = np.stack(all_xys, axis = 0)
all_xys.shape

(8793, 2422, 2)

In [30]:
np.save('/home/dangnh36/datasets/ecg/processed/keypoints_by_model.npy', all_xys)

In [12]:
39.37007874015748 * 43.2

1700.7874015748032

In [15]:
1700 / 39.37007874015748

43.18

In [2]:
import logging
from typing import List, Optional, Tuple, Union

import numpy as np
import torch
from scipy.stats import chi2

logger = logging.getLogger(__name__)


def _clip(v, maxv, minv=0):
    return min(maxv, max(minv, v))

def cal_prob_outside_conf_interval(d, sigma_scale_factor=None, conf_interval=None):
    """
    Compute the maximum probability at the boundary of the x% confidence region
    for a d-dimensional standard multivariate normal distribution.

    Parameters:
        d (int): Number of dimensions (e.g., 3 for 3D).
        sigma_scale_factor: value of `sigma_scale_factor` sigma-rule,
            e.g 3.0 for dof=1 within 99.73% confident interval
        conf_interval (float): Confidence level in range[0, 1]

    Returns:
        float: Maximum probability density outside the confidence region.
    """
    if sigma_scale_factor is None:
        # Compute the chi-squared quantile (squared Mahalanobis distance)
        squared_maha = chi2.ppf(conf_interval, df=d)
    else:
        assert conf_interval is None
        squared_maha = sigma_scale_factor**2

    # Compute the PDF value at that quantile distance
    prob = np.exp(-0.5 * squared_maha)
    return prob

In [8]:
cal_prob_outside_conf_interval(1, sigma_scale_factor = 3.0)

0.011108996538242308

In [12]:
import cv2
import numpy as np

def test_homography_scaling():
    # 1. Define Shapes (Height, Width)
    h_src, w_src = 32, 50
    h_dst, w_dst = 64, 100

    print(f"Source Shape: ({h_src}, {w_src})")
    print(f"Target Shape: ({h_dst}, {w_dst})")
    print("-" * 30)

    # # 2. Define the 4 Corners of the Source Image
    # # Coordinate format: (x, y)
    # # Order: Top-Left, Top-Right, Bottom-Right, Bottom-Left
    # src_pts = np.array([
    #     [0, 0],          # TL
    #     [w_src, 0],      # TR
    #     [w_src, h_src],  # BR
    #     [0, h_src]       # BL
    # ], dtype=np.float32)

    # # 3. Define the 4 Corners of the Destination Image
    # dst_pts = np.array([
    #     [0, 0],          # TL
    #     [w_dst, 0],      # TR
    #     [w_dst, h_dst],  # BR
    #     [0, h_dst]       # BL
    # ], dtype=np.float32)

    # 2. Define the 4 Corners of the Source Image
    # Coordinate format: (x, y)
    # Order: Top-Left, Top-Right, Bottom-Right, Bottom-Left
    src_pts = np.array([
        [1, 1],          # TL
        [5, 1],      # TR
        [5, 7],  # BR
        [1, 7]       # BL
    ], dtype=np.float32)

    # 3. Define the 4 Corners of the Destination Image
    dst_pts = np.array([
        [2, 2],          # TL
        [10, 2],      # TR
        [10, 14],  # BR
        [2, 14]       # BL
    ], dtype=np.float32)

    src_pts = src_pts - 0.5
    dst_pts = dst_pts - 0.5

    # 4. Compute Homography (Source -> Destination)
    # This matrix M maps a point in src to a point in dst: dst_pt = M @ src_pt
    H = cv2.getPerspectiveTransform(src_pts, dst_pts)

    # 5. Print Result
    print("Calculated Homography Matrix H:")
    print(H)
    print("-" * 30)

    # 6. Verification
    # Expected: Scaling matrix [[2, 0, 0], [0, 2, 0], [0, 0, 1]]
    expected_sx = w_dst / w_src
    expected_sy = h_dst / h_src
    
    print(f"Expected Scaling Factors: Sx={expected_sx}, Sy={expected_sy}")
    print(f"Matrix Scale X (H[0,0]):  {H[0,0]}")
    print(f"Matrix Scale Y (H[1,1]):  {H[1,1]}")

if __name__ == "__main__":
    test_homography_scaling()

Source Shape: (32, 50)
Target Shape: (64, 100)
------------------------------
Calculated Homography Matrix H:
[[ 2.00000000e+00 -1.52934817e-17  5.00000000e-01]
 [ 5.35836807e-17  2.00000000e+00  5.00000000e-01]
 [ 3.58509518e-17 -1.15648232e-18  1.00000000e+00]]
------------------------------
Expected Scaling Factors: Sx=2.0, Sy=2.0
Matrix Scale X (H[0,0]):  2.0000000000000004
Matrix Scale Y (H[1,1]):  2.0

In [25]:
from scipy import ndimage
import numpy as np
a = np.arange(12.).reshape((4, 3))
a[0, 1] = 1.5
print(a)
ndimage.map_coordinates(a, [[0.5, 2], [0.5, 1]], order=1)

[[ 0.   1.5  2. ]
 [ 3.   4.   5. ]
 [ 6.   7.   8. ]
 [ 9.  10.  11. ]]

array([0., 7.])

In [24]:
a[:2, :2].mean()

2.125